[package]
name = "oprs-api-types"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
oprs-core = { path = "../oprs-core" }
oprs-data = { path = "../oprs-data" }
oprs-dry-run = { path = "../oprs-dry-run" }

[lib]
path = "src/lib.rs"
